export const REPLACEMENT = {
  "solve": "work through",
  "like": "a fan of/be into",
  "talk about": "talk through",
  "contact": "get hold of",
  "finally": "end up doing",
  "exercise": "work out",
  "discuss": "go through/over",
  "read": "go through/over",
  "refuse": "turn down",
  "support": "go for/get behind",
  "fire": "let...go",
  "get ready": "gear up",
  "agreement": "buy in",
  "accept": "approve of",
  "agree": "approve of",
  "arrange": "get in",
  "I'm fine": "I'm good/great",
  "No.": "I don't think so./I'm good.",
  "currently": "at this point",
  "at that time": "at that point",
  "then": "at that point",
  "at some time": "at some point",
  "seldom": "rarely",
  "so far": "thus far/up to date",
  "in the future": "down the road",
  "from now on": "going/moving forward",
  "related to": "pertaining to",
  "doing": "in the middle of doing",
  "while": "whereas",
  "make sense": "add up",
  "make progress": "get traction",
  "colleagues": "coworker",
  "in summary": "in a nutshell",
  "employees": "workforce",
  "go to": "head to",
  "don't understand": "over my head",
  "under": "underneath",
  "table": "matrix",
  "Excel": "spreadsheet",
  "hope": "promise",
  "I think": "I guess",
  "come up with": "figure out",
  "futhermore": "on top of that",
  "face": "tackle",
  "talk": "speak",
  "method": "approach",
  "way": "approach",
  "go on": "move on",
  "appear like": "come across like",
  "all people": "across the board",
  "That's all": "All right",
  "OK": "sounds good",
  "if so": "if that's the case",
  "your decision": "up to you/your call/at your discretion",
  "discuss with you": "run by you/bounce off you"
};
